import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import './globals.css';


const inter = Fira_Code({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={cn('min-h-screen bg-background font-inter antialiased', inter.variable)}>{children}</body>
    </html>
  );
}
